extend type Mutation {
  """
  ✨ Insert a single `Document` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  document_insert(
    """
    Data object to insert into the table.
    """
    data: Document_Data!
  ): Document_KeyOutput! @fdc_generated(from: "Document", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DocumentFolder` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  documentFolder_insert(
    """
    Data object to insert into the table.
    """
    data: DocumentFolder_Data!
  ): DocumentFolder_KeyOutput! @fdc_generated(from: "DocumentFolder", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Folder` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  folder_insert(
    """
    Data object to insert into the table.
    """
    data: Folder_Data!
  ): Folder_KeyOutput! @fdc_generated(from: "Folder", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Document` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  document_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Document_Data!]!
  ): [Document_KeyOutput!]! @fdc_generated(from: "Document", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DocumentFolder` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  documentFolder_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DocumentFolder_Data!]!
  ): [DocumentFolder_KeyOutput!]! @fdc_generated(from: "DocumentFolder", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Folder` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  folder_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Folder_Data!]!
  ): [Folder_KeyOutput!]! @fdc_generated(from: "Folder", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Document` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Document`.
  """
  document_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Document_Data!
  ): Document_KeyOutput! @fdc_generated(from: "Document", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DocumentFolder` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DocumentFolder`.
  """
  documentFolder_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DocumentFolder_Data!
  ): DocumentFolder_KeyOutput! @fdc_generated(from: "DocumentFolder", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Folder` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Folder`.
  """
  folder_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Folder_Data!
  ): Folder_KeyOutput! @fdc_generated(from: "Folder", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Document` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Document`.
  """
  document_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Document_Data!]!
  ): [Document_KeyOutput!]! @fdc_generated(from: "Document", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DocumentFolder` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DocumentFolder`.
  """
  documentFolder_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DocumentFolder_Data!]!
  ): [DocumentFolder_KeyOutput!]! @fdc_generated(from: "DocumentFolder", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Folder` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Folder`.
  """
  folder_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Folder_Data!]!
  ): [Folder_KeyOutput!]! @fdc_generated(from: "Folder", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Document` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Document` or `null` if not found.
  """
  document_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Document_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Document_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Document_Data!
  ): Document_KeyOutput @fdc_generated(from: "Document", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DocumentFolder` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DocumentFolder` or `null` if not found.
  """
  documentFolder_update(
    """
    The key used to identify the object.
    """
    key: DocumentFolder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DocumentFolder_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DocumentFolder_Data!
  ): DocumentFolder_KeyOutput @fdc_generated(from: "DocumentFolder", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Folder` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Folder` or `null` if not found.
  """
  folder_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Folder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Folder_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Folder_Data!
  ): Folder_KeyOutput @fdc_generated(from: "Folder", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Document` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  document_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Document_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Document_Data!
  ): Int! @fdc_generated(from: "Document", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DocumentFolder` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  documentFolder_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DocumentFolder_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DocumentFolder_Data!
  ): Int! @fdc_generated(from: "DocumentFolder", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Folder` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  folder_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Folder_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Folder_Data!
  ): Int! @fdc_generated(from: "Folder", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Document` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  document_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Document_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Document_FirstRow
  ): Document_KeyOutput @fdc_generated(from: "Document", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DocumentFolder` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  documentFolder_delete(
    """
    The key used to identify the object.
    """
    key: DocumentFolder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DocumentFolder_FirstRow
  ): DocumentFolder_KeyOutput @fdc_generated(from: "DocumentFolder", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Folder` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  folder_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Folder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Folder_FirstRow
  ): Folder_KeyOutput @fdc_generated(from: "Folder", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Document` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  document_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Document_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Document", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DocumentFolder` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  documentFolder_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DocumentFolder_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DocumentFolder", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Folder` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  folder_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Folder_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Folder", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
