extend type Document {
  """
  ✨ List `DocumentFolder` objects in a one-to-many relationship (where `DocumentFolder`.`document` is this object).
  """
  documentFolders_on_document(
    """
    Filter condition to narrow down the query results.
    """
    where: DocumentFolder_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DocumentFolder_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DocumentFolder_Having
  ): [DocumentFolder!]! @fdc_generated(from: "DocumentFolder.document", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Folder` objects using `DocumentFolder` as the join table (a `DocumentFolder` object exists where its `document` is this and its `folder` is that).
  """
  folders_via_DocumentFolder(
    """
    Filter condition to narrow down the query results.
    """
    where: DocumentFolder_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DocumentFolder_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DocumentFolder_Having
  ): [Folder!]! @fdc_generated(from: "DocumentFolder", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Document", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Document` table.
  """
  _count: Int! @fdc_generated(from: "Document.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `extractedText` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  extractedText_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.extractedText", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `imageUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  imageUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.imageUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `lastModifiedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastModifiedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.lastModifiedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Document` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Document.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `lastModifiedAt` field in the `Document` table.
  """
  lastModifiedAt_min: Timestamp @fdc_generated(from: "Document.lastModifiedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Document` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Document.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `lastModifiedAt` field in the `Document` table.
  """
  lastModifiedAt_max: Timestamp @fdc_generated(from: "Document.lastModifiedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Document.id", purpose: GLOBAL_ID)
}
extend type DocumentFolder {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "DocumentFolder", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `DocumentFolder` table.
  """
  _count: Int! @fdc_generated(from: "DocumentFolder.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DocumentFolder` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DocumentFolder.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DocumentFolder` table where the `documentId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  documentId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DocumentFolder.documentId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DocumentFolder` table where the `folderId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  folderId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DocumentFolder.folderId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `DocumentFolder` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "DocumentFolder.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `DocumentFolder` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "DocumentFolder.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "DocumentFolder.documentId,folderId", purpose: GLOBAL_ID)
}
extend type Folder {
  """
  ✨ List `DocumentFolder` objects in a one-to-many relationship (where `DocumentFolder`.`folder` is this object).
  """
  documentFolders_on_folder(
    """
    Filter condition to narrow down the query results.
    """
    where: DocumentFolder_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DocumentFolder_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DocumentFolder_Having
  ): [DocumentFolder!]! @fdc_generated(from: "DocumentFolder.folder", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Document` objects using `DocumentFolder` as the join table (a `DocumentFolder` object exists where its `folder` is this and its `document` is that).
  """
  documents_via_DocumentFolder(
    """
    Filter condition to narrow down the query results.
    """
    where: DocumentFolder_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DocumentFolder_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DocumentFolder_Having
  ): [Document!]! @fdc_generated(from: "DocumentFolder", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Folder", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Folder` table.
  """
  _count: Int! @fdc_generated(from: "Folder.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Folder` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Folder.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Folder` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Folder.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Folder` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Folder.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Folder` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Folder.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Folder` table where the `parentFolderId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  parentFolderId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Folder.parentFolderId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Folder` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Folder.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Folder` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Folder.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Folder` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Folder.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Folder.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `Document` objects in a one-to-many relationship (where `Document`.`user` is this object).
  """
  documents_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Document_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Document_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Document_Having
  ): [Document!]! @fdc_generated(from: "Document.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Folder` objects in a one-to-many relationship (where `Folder`.`user` is this object).
  """
  folders_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Folder_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Folder_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Folder_Having
  ): [Folder!]! @fdc_generated(from: "Folder.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `photoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  photoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.photoUrl", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
